config/routes.rb
Rails.application.routes.draw do
  # ルートパスはカード入力画面にしておく
  root to: 'cards#new'

  get 'cards/new', to: 'cards#new'
  get 'cards/show_hand', to: 'cards#show_hand'
  post 'cards/show_hand', to: 'cards#show_hand'

  # app/api/api.rbをマウント
  mount API => '/'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # require "pry"
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # 初期表示
  def new
  end

  # カードを判定し、結果を返す。新規画面と共通なのでそこに返す
  # システムエラーが生じた時は、それ用のエラーを返す
  def show_hand
    if request.get?
      redirect_to action: :new
    else
      begin
        @result = DeterminePokerHandService.new(params[:cards]).call
        @card = params[:cards]
        render :new
      rescue => e
        # ログを残す
        Rails.logger.error e.message
        @result = {error: '何らかのエラーが発生しました。詳細はサイト運営にお問い合わせください'}
        render :new
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<div class='poker'>
  <div class='container'>
    <% if @result.present? && @result[:error].present? %>
      <div class='alert alert-danger alert-dismissible' role='alert'>
        <span><%= @result[:error] %></span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end%>
    <h1>Check a Poker Hand</h1>
    <div class='content'>
      <div class='form-group row align-items-center'>
        <br><small class='card-description form-text text-muted'>トランプカードを半角空白区切りで5枚入力してください</small>
        <%= form_tag(cards_show_hand_path, method: :post) do %>
          <div class='card-form'>
            <%= text_field_tag :cards, '', {class: 'card-text-form', placeholder: 'S10 H10 D5 C10 H5', value: "#{@card}"} %>
          </div>
          <div class='start-btn'>
            <%= submit_tag 'Check', class: 'btn btn-primary'%>
          </div>
        <% end %>
      </div>
      <div class='poker-hand'>
        <span><%= @result[:hand_name] if @result.present? %></span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>AtoneNoShirenApp</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>